name: fallback-gpu
description: GPU fallback using Mistral Inference engine
maintainer: Canonical Ltd
devices:
  all:
    - type: cpu
  any:
    - type: gpu
      bus: pci
      vendor-id: 0x10de # Nvidia Corporation
      # model_ids: [ ]
      # vram: 4G
      # compute_capability: 7.0
memory: 16G
disk-space: 20G
components:
  - mistral-inference
  - model

configurations:
  max-tokens: 35
  temperature: 0.7
  num-pipeline-ranks: 1
  instruct: false
