name: hardware-info
base: core24
version: git
summary: Prints a summary of host hardware
description: |
  This application scans the host system and creates a summary of the available hardware.
  The summary is provided in JSON format for other applications to consume.

grade: devel
confinement: strict

# We require access to the pci ids database file to look up vendor and product names. We download and include this file in a part.
layout:
  /usr/share/misc/pci.ids:
    bind-file: $SNAP/pci.ids

parts:
  system-utilities:
    plugin: nil
    stage-packages:
      - pciutils
      - nvidia-utils

  # To use `version: git` in this file, we require git as a build dependency.
  # This is fixed but not published yet. See https://github.com/canonical/snapcraft/issues/4944
  git:
    plugin: nil
    build-packages:
      - git

  hardware-info-cli:
    plugin: go
    build-snaps:
      - go/latest/stable
    source: .
    source-type: local

  pci-ids:
    plugin: dump
    source: https://pci-ids.ucw.cz/v2.2/pci.ids
    source-type: file

apps:
  hardware-info:
    plugs:
      - hardware-observe
      - opengl
    command: bin/hardware-info
