name: Run Go tests

on: [push]

jobs:
  test-selector:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Run tests
        run: go test -v -failfast ./selector
