#!/bin/bash -e

go test -count 1 -failfast ./pkg/constants/...
go test -count 1 -failfast ./pkg/engines/...
go test -count 1 -failfast ./pkg/hardware_info/...
go test -count 1 -failfast ./pkg/selector/...
go test -count 1 -failfast ./pkg/snap_store/...
go test -count 1 -failfast ./pkg/types/...
go test -count 1 -failfast ./pkg/utils/...
