name: generic-cuda
description: Generic stack for Nvidia GPUs using CUDA. All major CUDA versions are targeted.
vendor: Canonical Ltd
grade: devel
devices:
  all:
    - type: cpu
      architecture: amd64
      flags: [sse4_2, f16c, fma, avx, avx2]
    - type: gpu
      bus: pci
      vendor-id: 0x10de # Nvidia Corporation
      # model-ids: [ ]
      vram: 5G
      # compute-capability: 5.0
memory: 2G
disk-space: 5G
components:
  - llamacpp-cuda
  - model-q4-k-m-gguf
configurations:
  engine: llamacpp-cuda
  model: model-q4-k-m-gguf
