name: example-memory
description: Example stack for legacy CPUs, offering full accuracy but very high memory use
vendor: Canonical Ltd
grade: stable
devices:
  any:
    - type: cpu
      manufacturer-id: AuthenticAMD
    - type: cpu
      manufacturer-id: GenuineIntel
memory: 35G
disk-space: 29G
components:
  - llamacpp
  - model-f32-gguf
configurations:
  engine: llamacpp
  model: model-f32-gguf
