name: ampere
description: Test ampere selection
vendor: Canonical Ltd
grade: stable
devices:
  any:
    - type: cpu
      architecture: arm64
      implementer-id: 0xc0 # Ampere
memory: 4G
disk-space: 5G
components:
  - llamaaio
  - model-q4-k-m-gguf
configurations:
  engine: llamaaio
  model: model-q4-k-m-gguf
