name: example-cpu-avx512
description: Example stack for modern CPUs, offering good accuracy with low footprints
maintainer: Canonical Ltd
grade: stable
devices:
  any:
    - type: cpu
      architectures: [amd64]
      flags: [sse4_2, f16c, fma, avx, avx2, avx512f, avx512dq, avx512bw]
memory: 8G
disk-space: 5G
components:
  - llamacpp-avx512
  - model-q4-k-m-gguf
configurations:
  engine: llamacpp-avx512
  model: model-q4-k-m-gguf
