package:
  verbose: false
  http.port: 8322
  http.host: "127.0.0.1"
  webui.http.port: 8323
  webui.http.host: "127.0.0.1"
user:
  user-test-key: "user-test-value"
engine:
  engine-test-key: "engine-test-value"
