name: stack-utils
base: core24
version: git
summary: Utilities for selecting hardware optimised stacks
description: |
  These utilities help decide which components should be installed on a particular system.

grade: devel
confinement: strict

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/intel-opencl:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/intel-opencl

parts:
  system-utilities:
    plugin: nil
    stage-packages:
      - pciutils
      - nvidia-utils
      - clinfo
      - mesa-opencl-icd
      - ocl-icd-libopencl1
      - on amd64:
        - intel-opencl-icd

  # To use `version: git` in this file, we require git as a build dependency.
  # This is fixed but not published yet. See https://github.com/canonical/snapcraft/issues/4944
  git:
    plugin: nil
    build-packages:
      - git

  go-clis:
    plugin: go
    build-snaps:
      - go/1.24/stable
    source: .
    source-type: local

apps:
  hardware-info:
    environment:
      OCL_ICD_VENDORS: "$SNAP/etc/OpenCL/vendors"
    plugs:
      - hardware-observe
      - opengl
      - network
    command: bin/hardware-info

  select-stack:
    plugs:
      - home
    command: bin/select-stack

  stack:
    plugs:
      - home
    command: bin/stack
