name: ml-snap-utils
base: core24
version: git
summary: Utilities for snapping ML workloads
description: |
  These utilities helps decide which components should be installed on a particular system.

grade: devel
confinement: strict

# We require access to the pci ids database file to look up vendor and product names. We download and include this file in a part.
layout:
  /usr/share/misc/pci.ids:
    bind-file: $SNAP/pci.ids

parts:
  system-utilities:
    plugin: nil
    stage-packages:
      - pciutils
      - nvidia-utils

  # To use `version: git` in this file, we require git as a build dependency.
  # This is fixed but not published yet. See https://github.com/canonical/snapcraft/issues/4944
  git:
    plugin: nil
    build-packages:
      - git

  go-clis:
    plugin: go
    build-snaps:
      - go/latest/stable
    source: .
    source-type: local

  pci-ids:
    plugin: dump
    source: https://pci-ids.ucw.cz/v2.2/pci.ids
    source-type: file

apps:
  hardware-info:
    plugs:
      - hardware-observe
      - opengl
      - system-backup
    command: bin/hardware-info

  select-stack:
    plugs:
      - home
    command: bin/select-stack
