name: ml-snap-utils
base: core24
version: git
summary: Utilities for snapping ML workloads
description: |
  These utilities helps decide which components should be installed on a particular system.

grade: devel
confinement: strict

# We require access to the pci ids database file to look up vendor and product names. We download and include this file in a part.
layout:
  /usr/share/misc/pci.ids:
    bind-file: $SNAP/pci.ids

parts:
  system-utilities:
    plugin: nil
    stage-packages:
      - pciutils
      - nvidia-utils
      - clinfo

  # TODO: move to a component
  # Source: https://github.com/canonical/openvino-ai-plugins-gimp-snap/blob/be8968938844436e48a1a94643c8e95b43062653/snap/snapcraft.yaml#L119-L150
  opencl-driver:
    # Includes all the compute runtime and OpenCL bits needed for Intel GPU support
    plugin: nil
    build-packages:
      - wget
    override-build: |
      mkdir -p neo
      cd neo
      # Install Intel graphics compiler and compute runtime
      # This is required to enable GPU support for OpenVINO
      # https://docs.openvino.ai/2024/get-started/configurations/configurations-intel-gpu.html
      wget https://github.com/intel/intel-graphics-compiler/releases/download/v2.5.6/intel-igc-core-2_2.5.6+18417_amd64.deb
      wget https://github.com/intel/intel-graphics-compiler/releases/download/v2.5.6/intel-igc-opencl-2_2.5.6+18417_amd64.deb
      wget https://github.com/intel/compute-runtime/releases/download/24.52.32224.5/intel-level-zero-gpu_1.6.32224.5_amd64.deb
      wget https://github.com/intel/compute-runtime/releases/download/24.52.32224.5/intel-opencl-icd_24.52.32224.5_amd64.deb
      wget https://github.com/intel/compute-runtime/releases/download/24.52.32224.5/libigdgmm12_22.5.5_amd64.deb
      dpkg --root=$CRAFT_PART_INSTALL --force-all -i *.deb
      # update paths to the Intel Installable Client Drivers (ICDs) for OpenCL
      intel_icd="${CRAFT_PART_INSTALL}"/etc/OpenCL/vendors/intel.icd
      intel_icd_so_path=$(cat ${intel_icd})
      base_path="/snap/${SNAPCRAFT_PROJECT_NAME}/current"
      echo "${base_path}""${intel_icd_so_path}" > "${intel_icd}"
      intel_legacy1_icd="${CRAFT_PART_INSTALL}"/etc/OpenCL/vendors/intel_legacy1.icd
      if [ -f ${intel_legacy1_icd} ]; then
        intel_legacy1_icd_so_path=$(cat ${intel_legacy1_icd})
        echo "${base_path}""${intel_legacy1_icd_so_path}" > "${intel_legacy1_icd}"
      fi
      # fix broken sym links
      cd "${CRAFT_PART_INSTALL}"
      ln -sf "${base_path}"/usr/bin/ocloc-24.39.1 etc/alternatives/ocloc
      ln -sf "${base_path}"/etc/alternatives/ocloc usr/bin/ocloc
      craftctl default

  # To use `version: git` in this file, we require git as a build dependency.
  # This is fixed but not published yet. See https://github.com/canonical/snapcraft/issues/4944
  git:
    plugin: nil
    build-packages:
      - git

  go-clis:
    plugin: go
    build-snaps:
      - go/1.24/stable
    source: .
    source-type: local

  pci-ids:
    plugin: dump
    source: https://pci-ids.ucw.cz/v2.2/pci.ids
    source-type: file

apps:
  hardware-info:
    plugs:
      - hardware-observe
      - opengl
    environment:
      OCL_ICD_VENDORS: "$SNAP/etc/OpenCL/vendors"
    command: bin/hardware-info

  select-stack:
    plugs:
      - home
    command: bin/select-stack
