#!/bin/bash -eu

tag="snap.$SNAP_INSTANCE_NAME.hook.post-refresh"

# Redirect stdout to stdout+syslog
exec 1> >(tee >(logger --tag=$tag))
# Redirect stderr to stderr+syslog
exec 2> >(logger --stderr --priority error --tag=$tag)

#
# Override default configurations
#
"$SNAP/bin/set-default-config.sh"

#
# WSL workaround
#
# With a layout we bind $SNAP_COMMON/usr/lib/wsl to /usr/lib/wsl.
# The layout automatically creates the source directory if it does not exist.
# We then create symlinks in this dir for the lib and drivers subdirectories,
# so they appear at /usr/lib/wsl/lib and /usr/lib/wsl/drivers in the layout.
# When refreshing, these symlinks might already exist, so force create.
ln -sfn /var/lib/snapd/hostfs/usr/lib/wsl/lib $SNAP_COMMON/usr/lib/wsl/lib
ln -sfn /var/lib/snapd/hostfs/usr/lib/wsl/drivers $SNAP_COMMON/usr/lib/wsl/drivers

#
# Refresh the active engine
#
modelctl use-engine --fix --assume-yes --fallback=cpu
